# Generated by Django 4.2.28 on 2026-02-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Job', 'Job'), ('Admit Card', 'Admit Card'), ('Form', 'Form'), ('Result', 'Result'), ('Scholarship', 'Scholarship')], max_length=50)),
                ('short_description', models.TextField(max_length=300)),
                ('full_description', models.TextField()),
                ('required_documents', models.TextField(help_text='List documents separated by commas or new lines')),
                ('eligibility', models.TextField(blank=True, help_text='Optional eligibility criteria')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('apply_link', models.URLField(blank=True, help_text='Official application link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
