# Generated by Django 4.2.28 on 2026-02-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='related_service',
            field=models.ForeignKey(blank=True, help_text='Service/Job/Form this inquiry is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='shop.service'),
        ),
    ]
