# Generated by Django 4.2.28 on 2026-02-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_inquiry_email_inquiry_name_inquiry_related_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Inquiries'},
        ),
    ]
